### PR TITLE
Fix _manually_evaluated_primal_status with VectorNonlinearOracle

### LINKED ISSUE #537: Wrong order of the nonlinear constraints in _manually_evaluated_primal_status
In the function [`_manually_evaluated_primal_status`](https://github.com/jump-dev/Ipopt.jl/blob/master/ext/IpoptMathOptInterfaceExt/MOI_wrapper.jl#L1551C10-L1579), the order of the constraints should be `[qp_cons, oracle, nlp_cons]` and not `[qp_cons, nlp_cons, oracle]`.

We use `[qp_cons, nlp_cons, oracle]` for the functions [`_setup_inner`](https://github.com/jump-dev/Ipopt.jl/blob/master/ext/IpoptMathOptInterfaceExt/MOI_wrapper.jl#L1299-L1307) and `row`.
We have the same issue in `UnoSolver.jl` if it is confirmed.

cc @odow @cvanaret

### PR DESCRIPTION
**Pull request by odow**
Closes #537

I also audited all of the other places where this could go wrong, and I think we're okay.

### CODE REVIEW

File: ext/IpoptMathOptInterfaceExt/MOI_wrapper.jl [hunk 1]
```diff
@@ -1552,16 +1552,14 @@ function _manually_evaluated_primal_status(model::Optimizer)
     x, g = model.inner.x, model.inner.g
     x_L, x_U = model.variables.lower, model.variables.upper
     g_L, g_U = copy(model.qp_data.g_L), copy(model.qp_data.g_U)
-    # Assuming constraints are guaranteed to be in the order:
-    # [qp_cons, nlp_cons, oracle]
+        for (_, cache) in model.vector_nonlinear_oracle_constraints
```
Comment (odow) [inline ext/IpoptMathOptInterfaceExt/MOI_wrapper.jl]:
```suggestion
    for (_, cache) in model.vector_nonlinear_oracle_constraints
```

**Comment by odow** [comment]
Introduced by https://github.com/jump-dev/Ipopt.jl/pull/511. Not enough testing Oscar. Learn your lessons.
